name: test_mobile
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  auto_route: ^8.2.0
  bloc: ^8.1.3
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  logger: ^2.3.0
  get_it: ^7.7.0
  jwt_decoder: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  hive_generator: ^2.0.1
  internet_connection_checker: ^1.0.0+1




dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: Futura
      fonts:
        - asset: fonts/FuturaPT-Heavy.ttf
          weight: 700
        - asset: fonts/FuturaPT-Light.ttf
          weight: 300
        - asset: fonts/FuturaPT-Medium.ttf
